[2024-09-01T22:33:21.692+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:33:21.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:33:21.707+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:33:21.706+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:33:22.041+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:33:22.024+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:33:22.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:33:22.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.526 seconds
[2024-09-01T22:33:52.375+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:33:52.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:33:52.711+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:33:52.709+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:33:52.771+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:33:52.759+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:33:52.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:33:52.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.500 seconds
[2024-09-01T22:34:24.188+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:34:24.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:34:24.512+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:34:24.510+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:34:25.422+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:34:25.323+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:34:25.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:34:25.675+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.865 seconds
[2024-09-01T22:34:57.022+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:34:57.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:34:59.898+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:34:59.826+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:35:00.089+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:35:00.062+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:35:00.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:35:00.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 3.255 seconds
[2024-09-01T22:35:31.041+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:35:31.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:35:31.052+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:35:31.051+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:35:31.381+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:35:31.373+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:35:31.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:35:31.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.413 seconds
[2024-09-01T22:36:01.957+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:36:01.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:36:01.969+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:36:01.968+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:36:02.022+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:36:02.014+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:36:02.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:36:02.066+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.207 seconds
[2024-09-01T22:36:32.472+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:36:32.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:36:32.479+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:36:32.479+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:36:32.533+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:36:32.528+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:36:32.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:36:32.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.121 seconds
[2024-09-01T22:37:03.074+0000] {processor.py:186} INFO - Started process (PID=118) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:37:03.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:37:03.131+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:37:03.130+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:37:04.272+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:37:04.262+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:37:04.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:37:04.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.376 seconds
[2024-09-01T22:37:34.952+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:37:34.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:37:34.958+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:37:34.958+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:37:35.143+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:37:35.122+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:37:35.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:37:35.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.258 seconds
[2024-09-01T22:38:05.454+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:38:05.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:38:05.484+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:38:05.462+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:38:05.895+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:38:05.863+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:38:05.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:38:06.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.716 seconds
[2024-09-01T22:38:36.605+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:38:36.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:38:36.622+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:38:36.622+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:38:36.675+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:38:36.668+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:38:36.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:38:36.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.359 seconds
[2024-09-01T22:39:07.187+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:39:07.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:39:07.191+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:39:07.191+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:39:07.224+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:39:07.220+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:39:07.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:39:07.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.079 seconds
[2024-09-01T22:39:37.750+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:39:37.751+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:39:37.756+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:39:37.755+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:39:37.799+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:39:37.784+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:39:37.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:39:37.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.143 seconds
[2024-09-01T22:40:08.137+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:40:08.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:40:08.142+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:40:08.142+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:40:08.177+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:40:08.168+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:40:08.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:40:08.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2024-09-01T22:40:38.797+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:40:38.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:40:38.803+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:40:38.803+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:40:38.828+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:40:38.826+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:40:38.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:40:38.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2024-09-01T22:41:09.281+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:41:09.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:41:09.287+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:09.286+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:41:09.319+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:09.316+0000] {dagbag.py:483} ERROR - Failed to bag_dag: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 217, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 943, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 760, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 478, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 837, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-09-01T22:41:09.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:41:09.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2024-09-01T22:41:15.485+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:41:15.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:41:15.491+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:15.490+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:41:15.764+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:41:21.486+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:21.485+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:etl_meterorologia
[2024-09-01T22:41:21.505+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:21.505+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:etl_meterorologia
[2024-09-01T22:41:21.517+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:21.517+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:etl_meterorologia
[2024-09-01T22:41:21.518+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:21.518+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:41:21.537+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:21.536+0000] {dag.py:3234} INFO - Creating ORM DAG for etl_meterorologia
[2024-09-01T22:41:21.555+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:21.555+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-08-31 00:00:00+00:00, run_after=2024-09-01 00:00:00+00:00
[2024-09-01T22:41:21.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 6.113 seconds
[2024-09-01T22:41:51.867+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:41:51.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:41:51.892+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:51.890+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:41:51.975+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:41:52.059+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:52.058+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:41:53.547+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:41:53.546+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:41:53.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.969 seconds
[2024-09-01T22:42:24.370+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:42:24.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:42:24.376+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:42:24.375+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:42:24.410+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:42:24.445+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:42:24.445+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:42:24.645+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:42:24.645+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:42:24.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.314 seconds
[2024-09-01T22:42:54.926+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:42:54.928+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:42:54.932+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:42:54.931+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:42:54.963+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:42:54.993+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:42:54.993+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:42:55.022+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:42:55.022+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:42:55.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.132 seconds
[2024-09-01T22:43:25.155+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:43:25.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:43:25.165+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:43:25.164+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:43:25.202+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:43:25.243+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:43:25.243+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:43:25.308+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:43:25.307+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:43:25.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.216 seconds
[2024-09-01T22:43:56.438+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:43:56.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:43:56.458+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:43:56.458+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:43:56.596+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:43:56.689+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:43:56.688+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:43:56.759+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:43:56.759+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:43:56.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.386 seconds
[2024-09-01T22:44:27.154+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:44:27.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:44:27.158+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:44:27.158+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:44:27.204+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:44:27.257+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:44:27.256+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:44:27.292+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:44:27.292+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:44:27.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.512 seconds
[2024-09-01T22:44:58.057+0000] {processor.py:186} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:44:58.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:44:58.065+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:44:58.064+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:44:58.101+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:44:58.163+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:44:58.163+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:44:58.416+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:44:58.415+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:44:58.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.406 seconds
[2024-09-01T22:45:28.812+0000] {processor.py:186} INFO - Started process (PID=233) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:45:28.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:45:28.816+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:45:28.816+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:45:28.844+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:45:28.885+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:45:28.885+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:45:29.088+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:45:29.088+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:45:29.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.312 seconds
[2024-09-01T22:45:44.695+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:45:44.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:45:44.705+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:45:44.704+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:45:44.764+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:45:44.901+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:45:44.901+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:45:45.043+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:45:45.043+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:45:45.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.510 seconds
[2024-09-01T22:46:15.596+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:46:15.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:46:15.602+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:46:15.602+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:46:15.639+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:46:15.676+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:46:15.676+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:46:15.718+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:46:15.717+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:46:15.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.159 seconds
[2024-09-01T22:46:46.056+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:46:46.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:46:46.061+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:46:46.060+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:46:46.100+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:46:46.131+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:46:46.131+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:46:46.158+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:46:46.158+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:46:46.183+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.134 seconds
[2024-09-01T22:47:16.575+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag.py
[2024-09-01T22:47:16.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-01T22:47:16.580+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:47:16.579+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-01T22:47:16.613+0000] {processor.py:925} INFO - DAG(s) 'etl_meterorologia' retrieved from /opt/airflow/dags/dag.py
[2024-09-01T22:47:16.639+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:47:16.639+0000] {dag.py:3211} INFO - Sync 1 DAGs
[2024-09-01T22:47:16.669+0000] {logging_mixin.py:190} INFO - [2024-09-01T22:47:16.669+0000] {dag.py:4138} INFO - Setting next_dagrun for etl_meterorologia to 2024-09-01 00:00:00+00:00, run_after=2024-09-02 00:00:00+00:00
[2024-09-01T22:47:16.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.309 seconds
